/** GET ALL BASES */
export const GET_ALL_BASES_BEGIN = 'GET_ALL_BASES_BEGIN'
export const GET_ALL_BASES_SUCCESS = 'GET_ALL_BASES_SUCCESS'
export const GET_ALL_BASES_ERROR = 'GET_ALL_BASES_ERROR'

/** GET ALL TABLES */
export const GET_ALL_TABLES_BEGIN = 'GET_ALL_TABLES_BEGIN'
export const GET_ALL_TABLES_SUCCESS = 'GET_ALL_TABLES_SUCCESS'
export const GET_ALL_TABLES_ERROR = 'GET_ALL_TABLES_ERROR'